safe: false
source: .
destination: ./_site
plugins_dir: ./_plugins
highlighter: rouge
markdown: kramdown
exclude: ['.git', '.travis.yml', '.travis.d', '.sass-cache', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'LICENSE.md', '.asset-cache', 'Dockerfile', '_scripts', 'vendor/']
encoding: utf-8

plugins:
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-last-modified-at

url: http://conferences.sigcomm.org
baseurl: /acm-icn/2022

# Configuration for site
title: ACM ICN 2022
logo:
  image: icn22-logo.png
  info: ACM ICN 2022, Osaka, Japan

# ACM ICN'2021 tracking
google_analytics_id: G-P5JWG4LM0B

program:
  # If the specified file doesn't exist, there will be command-line dialog to create it
  # (Currently hardcoded for a dummy robot.mcrobot.jr@gmail.com account permissions)
  google_client_id: .travis.d/google_client_id.json
  # Google spreadsheet with the conference data
  spreadsheet: 1BheA-g9ZqpCV94Ap3We1qL-dPbnHWF48sn9nHu72SEU

program-at-glance:
  google_client_id: .travis.d/google_client_id.json
  spreadsheet:
    - 1i1Qe4KUOmScVHVFJOu-sDsehFtE1Uhz9Tfm7z_MS__o
  
assets:
  sources:
    - _assets/css
    - _assets/images
    - _assets/fonts
    - _assets/js
    - _assets/bower
    - _assets/misc
    - _assets/files
    - .sass-cache

  plugins:
    css:
      autoprefixer:
        browsers:
          - "last 2 versions"
          - "IE > 9"

    img: { optim: {}, magick: {} }
